rugk/offline-qr-code

src/_locales/de/messages.json
src/_locales/en/messages.json
src/background.js

Add a context menu entry if a link is selected

---

.eslintignore
CONTRIBUTING.md
LICENSE.md
src/common/common.js
src/options.html
src/popup/lib/qrcodegen.js
src/popup/qrcode.html
src/popup/qrcode.js

Fixes https://github.com/rugk/offline-qr-code/issues/23

SVG support

---

src/common/common.css
src/common/variables.css
src/default.css
src/options.css
src/options.html
src/popup/qrcode.css
src/popup/qrcode.html

Hi @rugk 
I have made the changes as discussed for the issue #68 . Kindly let me know if anything is incorrect from my side. Thanks, for giving me a chance to contribute!!

Css variable

---

src/popup/qrcode.js

- Added variable initialClick to control when the qrCode is resized.

Fixed #102 feature 'Remember last size'.

---

README.md
assets/texts/de/amoDescription.html
assets/texts/de/privacy.txt
assets/texts/en/amoDescription.html
assets/texts/en/privacy.txt

Improve texts & Readme

---

README.md
assets/texts/en/amoDescription.html

I just fixed some small mistakes which do not influence the content.

Fix some typo, grammar and word choice issues

---

CONTRIBUTING.md
src/common/common.js
src/common/modules/Localizer.js

As mentioned in https://github.com/rugk/offline-qr-code/issues/120

Rename localise to localize to be consistent

---

src/_locales/de/messages.json
src/_locales/en/messages.json
src/background/modules/ContextMenu.js
src/common/modules/ContextMenu.js
src/popup/modules/UserInterface.js

Fixes #88 
Add the underscore as an access key in Firefox 63+.

Add access key to context menus

---

assets/texts/tr/Changelog/1.3.html
assets/texts/tr/Changelog/1.3.md
assets/texts/tr/amoDescription.html
assets/texts/tr/amoSummary.txt
src/_locales/tr/messages.json

1. Add Turkish changelog for 1.3
2. Improve some Turkish translation that did not sound native.
3. Translate "quiet zone" feature
4. Translate access keys
The first letter of the extension is trimmed. It might be because the first letter is "Ç" and there might be strange bug about it. I could not figure it out yet. When I do, I'll do another pull request.

Adjust new features to Turkish and add changelog

---

CONTRIBUTING.md

Fixed typos in CONTRIBUTING.md.

Fixed typos

---

src/_locales/de/messages.json
src/_locales/en/messages.json
src/options/options.html
src/popup/qrcode.html

Fixes https://github.com/rugk/offline-qr-code/issues/159

Localize aria-label for message boxes

---

src/common/modules/MobileHelper.js
src/common/modules/data/Tips.js

Fixes https://github.com/rugk/offline-qr-code/issues/162
**Edit:** Also fixes #150
Requires https://github.com/TinyWebEx/RandomTips/pull/2

Do not show shortcut tip if user customized shortcut

---

src/_locales/de/messages.json
src/_locales/en/messages.json
src/common/modules/data/Tips.js

Fixes https://github.com/rugk/offline-qr-code/issues/160

Add QR code reader tip on Android

---

CONTRIBUTING.md
src/_locales/de/messages.json
src/_locales/en/messages.json
src/common/modules/LanguageHelper.js
src/common/modules/data/Tips.js

Add translation/localisation tip

---

CONTRIBUTORS
src/_locales/tr/messages.json

Fixes #171
Requesting a potential review from @omurturan. Unless there are objections, this will be merged soon.

Update translation for tr from @serkanalgur

---

assets/texts/en/Changelog/next.md
assets/texts/tr/Changelog/1.4.html
assets/texts/tr/Changelog/1.4.md
assets/texts/tr/Changelog/1.5.html
assets/texts/tr/Changelog/1.5.md
assets/texts/tr/Changelog/next.md
src/_locales/tr/messages.json

:globe_with_meridians: Turkish Language files and changelog according to #138 & #170

Turkish Language Files and changelog updated.

---

assets/texts/fr/Changelog/1.6.html
assets/texts/fr/Changelog/1.6.md

Fixed errors in Changelog
Added line about the french translation

Changelog 1.6 - French translation 

---

assets/texts/de/amoDescription.html
assets/texts/de/amoSummary.txt
assets/texts/de/permissions.md
assets/texts/de/privacy.txt

Read through the german translation and fixed some minor errors (mostly missing comma's) ✏️

Minor grammar and syntax fixes for german translation

---

CONTRIBUTORS.md
assets/texts/en/Changelog/next.md
src/common/modules/data/DefaultSettings.js
src/common/variables.css
src/popup/modules/UserInterface.js
src/popup/qrcode.css

Fixes https://github.com/rugk/offline-qr-code/issues/186
Incorporates suggested changes from https://github.com/rugk/offline-qr-code/pull/201

Take two: close #186 (Automatic) dark mode

---

assets/texts/pt/Changelog/1.1.html
assets/texts/pt/Changelog/1.1.md
assets/texts/pt/Changelog/1.2.1.html
assets/texts/pt/Changelog/1.2.1.md
assets/texts/pt/Changelog/1.2.html
assets/texts/pt/Changelog/1.2.md
assets/texts/pt/Changelog/1.3.html
assets/texts/pt/Changelog/1.3.md
assets/texts/pt/Changelog/1.4.html
assets/texts/pt/Changelog/1.4.md
assets/texts/pt/Changelog/1.5.html
assets/texts/pt/Changelog/1.5.md
assets/texts/pt/Changelog/1.6.html
assets/texts/pt/Changelog/1.6.md
assets/texts/pt/amoDescription.html
assets/texts/pt/amoScreenshots.csv
assets/texts/pt/amoSummary.txt
assets/texts/pt/permissions.md
assets/texts/pt/privacy.txt
src/_locales/pt/messages.json

Fixes https://github.com/rugk/offline-qr-code/issues/206

Added portuguese translation

---

assets/texts/pt/Changelog/next.md
assets/texts/pt/amoSummary.txt

Some other translations were also fixed.

Adjusted the amoSummary.txt file to fit in 250 characters

---

CONTRIBUTORS.md
assets/texts/en/Changelog/next.md
src/_locales/ru/messages.json

Fixes https://github.com/rugk/offline-qr-code/issues/217

Add Russian translation

---

src/options/options.html

#96 
I changed the position of error message in html to top of color settings, but i am not sure if this is what you meant. Please let me know if this is ok.

Change position of bad contrast error message

---

assets/texts/fr/amoDescription.html
src/_locales/fr/messages.json

Update French translation

---

assets/texts/en/permissions.md

Fixed a few errors

---

assets/texts/sk/Changelog/1.7.html
assets/texts/sk/Changelog/1.7.md
assets/texts/sk/amoDescription.html

Hi @rugk,
pull request is fixing few missing Slovak translations.

Small Slovak translation fixes

---

src/popup/modules/UserInterface.js

As discussed before.
Pretty printing may be required.
Closes #247

Filename generation for URL

---

src/_locales/pl/messages.json

Added Polish translation. I hope I got it right. If not, please excuse me.

Added Polish translation

---

.github/workflows/main.yml

As a test for now…
ref https://docs.github.com/en/github/finding-security-vulnerabilities-and-errors-in-your-code/configuring-code-scanning#changing-the-languages-that-are-analyzed

Add CodeQL CI

---

assets/texts/es/amoDescription.html
assets/texts/es/amoScreenshots.csv
assets/texts/es/amoSummary.txt
assets/texts/es/permissions.md
assets/texts/es/privacy.txt
src/_locales/es/messages.json

Greetings,
Attached you'll find my humble PR which localizes `messages.json` to Latin American Spanish. 
Any feedback will be appreciated. Looking forward to help more with this project.  (Will probably do `assets/texts` next sometime after work)
Thanks!

Added Spanish Translation

---

CONTRIBUTING.md

Fix broken link to Firefox Add-ons Reviews.

Update CONTRIBUTING.md to fix broken link

---

src/_locales/nl/messages.json

Here's a Dutch translation. Might be a bit wonky due to the fact that I'm not a native Dutch speaker, but I think it's fine. ^^
I've left some links untranslated because there are no Dutch equivalents.

Dutch translation

---

src/_locales/ro/messages.json

This pull request adds Romanian language support by adding a new locale "ro"
I would love to contribute to this project! I made sure the words made sense in context and that the translations match the meanings in English.

Add Romanian language support

---

CONTRIBUTORS.md
src/_locales/uk/messages.json

Add Ukrainian translation

---

CONTRIBUTORS.md
assets/texts/en/Changelog/next.md
src/_locales/zh_CN/messages.json

Closes #318 
Thanks @zhaiyusci

Add updated translations of zh_CN by @zhaiyusci

---

src/_locales/ar/messages.json
src/_locales/gr/messages.json

Hey! I have added a greek translation. I really liked working on this project!

Added Greek Translation

---

CONTRIBUTORS.md
src/_locales/ur/messages.json

I translated the messages.json file to Urdu under the directory `ur`. If there is any mistake please tell me.

Create Urdu translation for contents in messages.json.

---

assets/texts/es/amoSummary.txt

- Updated the first paragraph as it was translated too literally from English and looked a bit unnatural in Spanish. As a (desired) side effect, it was shortened.
-  Updated the second paragraph according to https://github.com/rugk/offline-qr-code/issues/330 which made sense to me too.
resolves #330

fix(i18n): Clean / shorten spanish amo summary

---

assets/texts/en/Changelog/next.md

Added a changelog entry for the new context menu item feature, which allows users to generate QR codes for the current page.

Add changelog entry for context menu feature

---

CONTRIBUTORS.md
src/_locales/fi/messages.json

Hello! There's the Finnish translation for `messages.json`. I'll add more translations later to the other files.

Add Finnish translation

---

assets/texts/ja/Changelog/1.8.html
assets/texts/ja/Changelog/1.8.md
assets/texts/ja/Changelog/1.9.html
assets/texts/ja/Changelog/1.9.md
assets/texts/ja/Changelog/next.md
assets/texts/ja/amoDescription.html
src/_locales/ja/messages.json

Update Japanese translation to track latest English version

Update Japanese translation

---

CONTRIBUTORS.md
src/_locales/he/messages.json

Add Hebrew translations for the following messages:
- permissionRequiredClipboardRead
- contextMenuItemConvertPageURL
- contextMenuItemConvertPageURLAccessKey
- contextMenuSaveImageCanvas
- contextMenuSaveImageCanvasAccessKey
- contextMenuSaveImageSvg
- contextMenuSaveImageSvgAccessKey
- optionContextMenuEnabled
- optionContextMenuEnabledDescr
- optionAutoGetClipboardContent
- buttonRequestPermission
- couldNotRequestPermission

Add Hebrew messages
